### ISSUE TITLE
Forgot to type the word "what"

### ISSUE THREAD

**Issue by kingsman142** [laboon/CS1632_Fall2016#1]
In the Deliverable 3 folder, in the Deliverable3.md file, in the 5th paragraph (after the bulleted points) under the "Format" section, the text should say "...shall have a description (a few sentences at most) of **what** they are testing...".  The original author forgot to include the word "what", possibly confusing current and future students reading the directions for this program.

**Comment by laboon** [comment]
You gotsta learn to do PRs, this would have been much easier for you...

Am going to look at the issue you emailed about tomorrow, never got a chance today.

**Comment by laboon** [comment]
Fixed in 6f7aff5dda7fdbcdc03575c06d1d9301f01096b9
